//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributorOfTasks
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicTask
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<short> PriorityID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
